extend:
  initializr:
    architectures:
      - id: "none"
        name: "None"
        default: true
      - id : "mvc"
        name: "MVC"
        default: false
        facets:
          - "web"
          - "thymeleaf"
          - "h2"
          - "jpa"
      - id: "microservice"
        name: "Microservice"
        default: false
        facets:
          - "web"
          - "jpa"
    gitpush:
      oauthapps:
        github:
          enabled: true
          clientid: 27c83ffc0f8fd2a9859b
          client-secret: aed126a9b6c3941f3a4768b2f37c6df810fcbb74
          oauth-uri: https://github.com/login/oauth/authorize
          redirect-uri: http://localhost:8080/login/oauth2/code

spring:
  cloud:
    azure:
      compatibility-verifier:
        enabled: false
      keyvault:
        secret:
          # set property-source-enabled to `true` if you want to use keyvault
          property-source-enabled: false
          property-sources:
            - name: key-vault-property-souece
              endpoint: ${input-your-keyvault-endpoint}
